CREATE TABLE user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(45) NOT NULL UNIQUE,
	password VARCHAR(45) NOT NULL UNIQUE,
	first_name VARCHAR(45) NOT NULL,
	middle_name VARCHAR(45) NOT NULL,
	last_name VARCHAR(45) NOT NULL,
	email VARCHAR(45) NOT NULL UNIQUE,
	role_id INT NOT NULL,
	CONSTRAINT fk_user_role_id FOREIGN KEY (role_id)
		REFERENCES role(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);